Repository jenkinsci/stapler, pull requests merged in 2019-08, with the labels that each got.

#165 A little bit of pom cleanup.
  jrebel/pom.xml
  pom.xml
Labels: chore

#168 acceptsGzip logic was inverted
  core/src/main/java/org/kohsuke/stapler/ResponseImpl.java
Labels: internal

#169 Enable Release Drafter
  .github/release-drafter.yml
Labels: chore

#164 [JENKINS-53322] Use standard dom4j distribution.
  jelly/pom.xml
  jelly/src/main/java/org/kohsuke/stapler/jelly/ContentTypeTag.java
  jelly/src/main/java/org/kohsuke/stapler/jelly/DefaultScriptInvoker.java
  jelly/src/main/java/org/kohsuke/stapler/jelly/HTMLWriterOutput.java
Labels: dependencies
