Repository jenkinsci/stapler, pull requests merged in 2020-12, with the labels that each got.

#198 Add stage's to Jenkinsfile
  Jenkinsfile
Labels: internal

#197 Don't use setAccessible, fixes illegal reflective access warnings
  core/src/main/java/org/kohsuke/stapler/lang/FieldRef.java
Labels: bug

#199 Quieter log
  core/src/main/java/org/kohsuke/stapler/lang/FieldRef.java
Labels: bug

#200 Better log message
  core/src/main/java/org/kohsuke/stapler/lang/FieldRef.java
Labels: documentation

#202 Convert `GString` to `String` when bridging to jelly.
  groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/JellyBuilder.java
Labels: bug

#201 Handle more cases of illegal reflective access
  core/src/main/java/org/kohsuke/stapler/RequestImpl.java
  core/src/main/java/org/kohsuke/stapler/lang/FieldRef.java
  core/src/main/java/org/kohsuke/stapler/lang/MethodRef.java
  core/src/main/java/org/kohsuke/stapler/util/IllegalReflectiveAccessLogHandler.java
Labels: bug
