Repository jenkinsci/stapler, pull requests merged in 2020-06, with the labels that each got.

#190 Improve message regarding duplicated annotated constructors (II)
  core/src/main/java/org/kohsuke/stapler/jsr269/ConstructorProcessor.java
  core/src/test/java/org/kohsuke/stapler/jsr269/ConstructorProcessorTest.java
Labels: enhancement

#185 Add spotbugs and findsecbugs
  core/pom.xml
  core/src/main/java/org/kohsuke/stapler/AbstractTearOff.java
  core/src/main/java/org/kohsuke/stapler/AcceptHeader.java
  core/src/main/java/org/kohsuke/stapler/AncestorImpl.java
  core/src/main/java/org/kohsuke/stapler/ClassDescriptor.java
  core/src/main/java/org/kohsuke/stapler/Dispatcher.java
  core/src/main/java/org/kohsuke/stapler/Facet.java
  core/src/main/java/org/kohsuke/stapler/ForwardToView.java
  core/src/main/java/org/kohsuke/stapler/HttpRedirect.java
  core/src/main/java/org/kohsuke/stapler/MetaClass.java
  core/src/main/java/org/kohsuke/stapler/MetaClassLoader.java
  core/src/main/java/org/kohsuke/stapler/ResponseImpl.java
  core/src/main/java/org/kohsuke/stapler/ScriptRequestDispatcher.java
  core/src/main/java/org/kohsuke/stapler/SingleLinkedList.java
  core/src/main/java/org/kohsuke/stapler/Stapler.java
  core/src/main/java/org/kohsuke/stapler/TearOffSupport.java
  core/src/main/java/org/kohsuke/stapler/TokenList.java
  core/src/main/java/org/kohsuke/stapler/bind/BoundObjectTable.java
  core/src/main/java/org/kohsuke/stapler/compression/CompressionFilter.java
  core/src/main/java/org/kohsuke/stapler/compression/UncaughtExceptionHandler.java
  core/src/main/java/org/kohsuke/stapler/config/ConfigurationLoader.java
  core/src/main/java/org/kohsuke/stapler/framework/AbstractWebAppMain.java
  core/src/main/java/org/kohsuke/stapler/framework/io/AtomicFileWriter.java
  core/src/main/java/org/kohsuke/stapler/framework/io/ByteBuffer.java
  groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/JellyBuilder.java
  groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/SimpleTemplateParser.java
  groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/StaplerClosureScript.java
  jelly/src/main/java/org/kohsuke/stapler/framework/adjunct/AdjunctManager.java
  jelly/src/main/java/org/kohsuke/stapler/jelly/CopyStreamTag.java
  jelly/src/main/java/org/kohsuke/stapler/jelly/DefaultScriptInvoker.java
  jelly/src/main/java/org/kohsuke/stapler/jelly/InternationalizedStringExpression.java
  jelly/src/main/java/org/kohsuke/stapler/jelly/JellyClassLoaderTearOff.java
  jelly/src/main/java/org/kohsuke/stapler/jelly/JellyFacet.java
  jelly/src/main/java/org/kohsuke/stapler/jelly/JellyRequestDispatcher.java
  jelly/src/main/java/org/kohsuke/stapler/jelly/ReallyStaticTagLibrary.java
  jelly/src/main/java/org/kohsuke/stapler/jelly/ResourceBundle.java
  jruby/src/main/java/org/kohsuke/stapler/jelly/jruby/RubyTemplateContainer.java
  jsp/src/main/java/org/kohsuke/stapler/jsp/RequestDispatcherWrapper.java
  jsp/src/main/java/org/kohsuke/stapler/tags/Include.java
  pom.xml
  src/spotbugs/spotbugs-excludes.xml
Labels: chore

#189 Update commons-fileupload to match that used in Jenkins
  core/pom.xml
  core/src/test/java/org/kohsuke/stapler/RequestImplTest.java
Labels: dependencies
