Repository jenkinsci/stapler, pull requests merged in 2021-08, with the labels that each got.

#243 Bump Jetty from 6.1.11 to 9.4.41.v20210516
  .github/dependabot.yml
  core/pom.xml
  core/src/test/java/org/kohsuke/stapler/compression/CompressionFilterTest.java
  core/src/test/java/org/kohsuke/stapler/interceptor/JsonOutputFilterTest.java
  core/src/test/java/org/kohsuke/stapler/test/JettyTestCase.java
  jelly/pom.xml
  pom.xml
Labels: dependencies

#256 Remove kk email contact
  docs/getting-started.adoc
Labels: documentation

#257 Ignore new versions of the Servlet API
  .github/dependabot.yml
Labels: chore

#258 Switch to `spotbugs-annotations`
  core/pom.xml
  core/src/main/java/org/kohsuke/stapler/AcceptHeader.java
  core/src/main/java/org/kohsuke/stapler/DispatchValidator.java
  core/src/main/java/org/kohsuke/stapler/EvaluationTrace.java
  core/src/main/java/org/kohsuke/stapler/Facet.java
  core/src/main/java/org/kohsuke/stapler/HttpRedirect.java
  core/src/main/java/org/kohsuke/stapler/HttpResponses.java
  core/src/main/java/org/kohsuke/stapler/LocaleDrivenResourceProvider.java
  core/src/main/java/org/kohsuke/stapler/ResponseImpl.java
  core/src/main/java/org/kohsuke/stapler/ScriptExecutor.java
  core/src/main/java/org/kohsuke/stapler/ScriptRequestDispatcher.java
  core/src/main/java/org/kohsuke/stapler/StaplerResponse.java
  core/src/main/java/org/kohsuke/stapler/StaplerResponseWrapper.java
  core/src/main/java/org/kohsuke/stapler/export/ClassAttributeBehaviour.java
  core/src/main/java/org/kohsuke/stapler/export/DataWriter.java
  core/src/main/java/org/kohsuke/stapler/export/JSONDataWriter.java
  core/src/main/java/org/kohsuke/stapler/export/Model.java
  core/src/main/java/org/kohsuke/stapler/export/ModelBuilder.java
  core/src/main/java/org/kohsuke/stapler/export/Property.java
  core/src/main/java/org/kohsuke/stapler/export/XMLDataWriter.java
  core/src/main/java/org/kohsuke/stapler/interceptor/RequirePOST.java
  core/src/main/java/org/kohsuke/stapler/json/JsonHttpResponse.java
  core/src/main/java/org/kohsuke/stapler/lang/Klass.java
  core/src/main/java/org/kohsuke/stapler/lang/KlassNavigator.java
  core/src/main/java/org/kohsuke/stapler/lang/MethodRef.java
  core/src/test/java/org/kohsuke/stapler/ClassDescriptorTest.java
  jelly/src/main/java/org/kohsuke/stapler/jelly/DefaultScriptInvoker.java
  jelly/src/main/java/org/kohsuke/stapler/jelly/JellyFacet.java
  jelly/src/main/java/org/kohsuke/stapler/jelly/ScriptInvoker.java
  jruby/src/main/java/org/kohsuke/stapler/jelly/jruby/RubyMethodRef.java
Labels: chore

#264 Disable flakey test
  jruby/src/test/java/org/kohsuke/stapler/jelly/jruby/haml/JRubyJellyHamlScriptTest.java
Labels: chore

#173 Adding tests to reproduce issue with JSONNull.
  core/src/test/java/org/kohsuke/stapler/export/JSONDataWriterTest.java
Labels: tests
