Repository jenkinsci/stapler, pull requests merged in 2021-05, with the labels that each got.

#216 Inline Guava's `Iterators#limit`
  core/src/main/java/org/kohsuke/stapler/export/Iterators.java
  core/src/main/java/org/kohsuke/stapler/export/Range.java
Labels: dependencies

#218 [INFRA-2908] Prepare to publish Stapler via JEP-229
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .mvn/extensions.xml
  .mvn/maven.config
  Jenkinsfile
  README.md
  core/pom.xml
  docs/compression.adoc
  docs/getting-started.adoc
  docs/i18n.adoc
  docs/jelly-taglib-ref.adoc
  docs/reference.adoc
  docs/stapler.png
  docs/stapler.vsd
  docs/taglib-jelly.xsd
  docs/taglib.xsd
  docs/what-is.adoc
  groovy/pom.xml
  groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/GroovyClassLoaderTearOff.java
  jelly/pom.xml
  jrebel/pom.xml
  jruby/pom.xml
  jsp/pom.xml
  pom.xml
  src/site/markdown/index.md
  src/site/resources/compression.html
  src/site/resources/getting-started.html
  src/site/resources/i18n.html
  src/site/resources/jelly-taglib-ref.html
  src/site/resources/reference.html
  src/site/resources/stapler.css
  src/site/resources/what-is.html
  src/site/site.xml
Labels: chore

#220 Replacing Guava’s `CacheBuilder` with Java Platform equivalents
  core/pom.xml
  core/src/main/java/org/kohsuke/stapler/AbstractTearOff.java
  core/src/main/java/org/kohsuke/stapler/CachingScriptLoader.java
  core/src/main/java/org/kohsuke/stapler/Function.java
  core/src/main/java/org/kohsuke/stapler/Optional.java
  core/src/main/java/org/kohsuke/stapler/ScriptLoadException.java
Labels: dependencies

#222 Bump `commons-discovery` from 0.4 to 0.5
  core/pom.xml
Labels: dependencies

#223 Bump various dependencies to latest versions
  core/pom.xml
  groovy/pom.xml
  jruby/pom.xml
Labels: dependencies

#224 Enable Dependabot
  .github/dependabot.yml
Labels: chore

#225 Stop using repackaged ASM; upgrade ASM to 9.1
  core/pom.xml
  core/src/main/java/org/kohsuke/stapler/ClassDescriptor.java
Labels: enhancement
