Repository jenkinsci/stapler, pull requests merged in 2021-04, with the labels that each got.

#212 [SECURITY-1097] Merge 1.262.1 back into master
  core/src/main/java/org/kohsuke/stapler/RequestImpl.java
Labels: bug

#214 [JENKINS-65442] json api improve performance when encoding unicode characters
  core/src/main/java/org/kohsuke/stapler/export/JSONDataWriter.java
Labels: enhancement

#215 Migrate from Guava's cache to `ConcurrentHashMap` in `JellyClassLoaderTearOff`
  jelly/src/main/java/org/kohsuke/stapler/jelly/JellyClassLoaderTearOff.java
Labels: dependencies
