Repository jenkinsci/stapler, pull requests merged in 2021-12, with the labels that each got.

#291 Bump parent POM from 1.65 to 1.69
  groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/JellyBuilder.java
  jelly/pom.xml
  jruby/pom.xml
  pom.xml
  src/spotbugs/spotbugs-excludes.xml
Labels: dependencies

#293 Clean up build
  core/pom.xml
  core/src/test/java/org/kohsuke/stapler/DispatcherTest.java
  core/src/test/java/org/kohsuke/stapler/Stapler2Test.java
  core/src/test/java/org/kohsuke/stapler/bind/JavaScriptProxyTest.java
  core/src/test/java/org/kohsuke/stapler/interceptor/JsonOutputFilterTest.java
  core/src/test/java/org/kohsuke/stapler/json/JsonBodyTest.java
  core/src/test/java/org/kohsuke/stapler/json/SubmittedFormTest.java
  groovy/pom.xml
  jelly/pom.xml
  jelly/src/test/java/org/kohsuke/stapler/jelly/BindTagJQueryTest.java
  jelly/src/test/java/org/kohsuke/stapler/jelly/BindTagTest.java
  jrebel/pom.xml
  jruby/pom.xml
  jsp/pom.xml
  pom.xml
Labels: chore

#296 INFRA-2908 Update URLs for new home in jenkinsci
  CHANGELOG.md
  core/src/test/java/org/kohsuke/stapler/RequestImplTest.java
  jruby/src/test/java/org/kohsuke/stapler/jelly/jruby/RubyKlassNavigatorTest.java
  pom.xml
Labels: chore

#298 Suppress a spurious SpotBugs warning that only appears on Java 11
  core/src/main/java/org/kohsuke/stapler/framework/io/LargeText.java
Labels: internal

#297 Replace deprecated `org.eclipse.jetty.util.ajax.JSON` with non-deprecated `net.sf.json`
  core/src/test/java/org/kohsuke/stapler/interceptor/JsonOutputFilterTest.java
Labels: internal

#300 Use Java 8 in annotation tests
  core/src/test/java/org/kohsuke/stapler/jsr269/ConstructorProcessorTest.java
  core/src/test/java/org/kohsuke/stapler/jsr269/ExportedBeanAnnotationProcessorTest.java
  core/src/test/java/org/kohsuke/stapler/jsr269/QueryParameterAnnotationProcessorTest.java
  core/src/test/java/org/kohsuke/stapler/jsr269/SourceGeneratingAnnotationProcessor.java
Labels: tests

#302 Use `@code` rather than `<tt>`
  core/src/main/java/org/kohsuke/stapler/AcceptHeader.java
  core/src/main/java/org/kohsuke/stapler/Ancestor.java
  core/src/main/java/org/kohsuke/stapler/DataBoundSetter.java
  core/src/main/java/org/kohsuke/stapler/HttpResponse.java
  core/src/main/java/org/kohsuke/stapler/MetaClass.java
  core/src/main/java/org/kohsuke/stapler/Stapler.java
  core/src/main/java/org/kohsuke/stapler/StaplerRequest.java
  core/src/main/java/org/kohsuke/stapler/StaplerResponse.java
  core/src/main/java/org/kohsuke/stapler/WebMethod.java
  core/src/main/java/org/kohsuke/stapler/config/ConfigurationLoader.java
  core/src/main/java/org/kohsuke/stapler/export/CustomExportedBean.java
  core/src/main/java/org/kohsuke/stapler/export/PythonDataWriter.java
  core/src/main/java/org/kohsuke/stapler/export/RubyDataWriter.java
  core/src/main/java/org/kohsuke/stapler/export/TypeUtil.java
  core/src/main/java/org/kohsuke/stapler/framework/errors/NoHomeDirError.java
  core/src/main/java/org/kohsuke/stapler/framework/io/LineEndNormalizingWriter.java
  core/src/main/java/org/kohsuke/stapler/json/JsonBody.java
  core/src/main/java/org/kohsuke/stapler/json/SubmittedForm.java
  jelly/src/main/java/org/kohsuke/stapler/framework/adjunct/AdjunctManager.java
  jelly/src/main/java/org/kohsuke/stapler/jelly/JellyClassTearOff.java
  jelly/src/main/java/org/kohsuke/stapler/jelly/ResourceBundle.java
  jsp/src/main/java/org/kohsuke/stapler/tags/Include.java
Labels: internal

#303 Run CI build on Java 11
  Jenkinsfile
Labels: internal

#304 Test on more configurations
  Jenkinsfile
  jruby/src/test/java/org/kohsuke/stapler/jelly/jruby/erb/JRubyJellyERbScriptTest.java
Labels: tests

#299 As of Java 9, _ is a keyword and may not be used as an identifier
  core/src/main/java/org/kohsuke/stapler/Function.java
  core/src/main/java/org/kohsuke/stapler/RequestImpl.java
  core/src/main/java/org/kohsuke/stapler/export/TypeUtil.java
Labels: internal

#310 Remove binaries
  core/lib/commons-beanutils-1.6-src.zip
  core/lib/commons-beanutils-1.6.jar
  core/lib/commons-jelly-1.0-src.zip
  core/lib/commons-jelly-1.0.jar
  core/lib/commons-jexl-1.0.jar
  core/lib/commons-logging.jar
  core/lib/dom4j-1.6.1.jar
  core/lib/groovy-all-1.0-JSR-06.jar
  core/lib/groovy.src.zip
  core/lib/jsp-api-2.0-20040521.jar
  core/lib/servletapi-2.3.jar
Labels: internal

#311 Remove JNDI support
  core/src/main/java/org/kohsuke/stapler/framework/AbstractWebAppMain.java
Labels: removed

#312 Adopt POM Code Convention
  core/pom.xml
  groovy/pom.xml
  jelly/pom.xml
  jrebel/pom.xml
  jsp/pom.xml
  pom.xml
Labels: internal

#313 Sort dependencies
  core/pom.xml
  groovy/pom.xml
  jelly/pom.xml
  jrebel/pom.xml
  jsp/pom.xml
  pom.xml
Labels: internal

#315 Dependency cleanup
  core/pom.xml
  jelly/pom.xml
  pom.xml
Labels: dependencies, java

#314 Bump Groovy from 2.4.12 to 2.4.21
  .github/dependabot.yml
  core/pom.xml
  groovy/pom.xml
Labels: dependencies, java
