Repository jenkinsci/stapler, pull requests merged in 2022-08, with the labels that each got.

#392 Upgrade JUnit from 4 to 5
  core/pom.xml
  groovy/pom.xml
  jelly/pom.xml
  pom.xml
Labels: skip-changelog

#393 Remove unnecessary assumption
  jelly/src/test/java/org/kohsuke/stapler/jelly/ResourceBundleTest.java
Labels: skip-changelog

#395 Simplify code for Java 11
  jelly/src/main/java/org/kohsuke/stapler/jelly/ResourceBundle.java
Labels: skip-changelog

#397 Double-checked locking for `WebApp#classMap`
  core/src/main/java/org/kohsuke/stapler/WebApp.java
Labels: internal

#394 Migrate from Hickory to Elementary
  core/pom.xml
  core/src/test/java/org/kohsuke/stapler/jsr269/ConstructorProcessorTest.java
  core/src/test/java/org/kohsuke/stapler/jsr269/ExportedBeanAnnotationProcessorTest.java
  core/src/test/java/org/kohsuke/stapler/jsr269/QueryParameterAnnotationProcessorTest.java
  core/src/test/java/org/kohsuke/stapler/jsr269/SourceGeneratingAnnotationProcessor.java
  core/src/test/java/org/kohsuke/stapler/jsr269/Utils.java
  pom.xml
Labels: test

#396 Remove ASM dependency
  core/pom.xml
  core/src/main/java/org/kohsuke/stapler/BytecodeReadingParanamer.java
  core/src/main/java/org/kohsuke/stapler/ClassDescriptor.java
  core/src/test/java/org/kohsuke/stapler/ClassDescriptorTest.java
Labels: internal

#399 Upgrade Maven Jellydoc and Stapler plugins
  jelly/pom.xml
  pom.xml
Labels: dependencies, java

#401 Remove `junit-bom` from managed dependencies
  pom.xml
Labels: dependencies, java

#402 Make `ClassLoaderValue` compatible with PowerMock
  core/src/main/java/org/kohsuke/stapler/ClassLoaderValue.java
Labels: bug
