Repository jenkinsci/stapler, pull requests merged in 2022-03, with the labels that each got.

#340 Add Java 17 to build/test matrix
  Jenkinsfile
  core/src/main/java/org/kohsuke/stapler/StaplerRequest.java
  jelly/src/main/java/org/kohsuke/stapler/framework/adjunct/package-info.java
Labels: test

#322 Fail fast when the frontend sends an invalid class name
  core/src/main/java/org/kohsuke/stapler/RequestImpl.java
Labels: bug

#344 Test coverage for `StaplerClosureScript._`
  groovy/src/test/java/org/kohsuke/stapler/jelly/groovy/GroovyClassLoaderTearOffTest.java
Labels: tests

#343 [JENKINS-67911] Stapler does not compile with Java 11
  groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/GroovierJellyScript.java
  groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/StaplerClosureScript.java
Labels: internal, squash-merge-me

#346 Use Eclipse Temurin, not AdoptOpenJDK, in CD action
  .github/workflows/cd.yaml
Labels: chore
