Repository jenkinsci/stapler, pull requests merged in 2022-06, with the labels that each got.

#368 chore: use jenkins infra maven cd reusable workflow
  .github/workflows/cd.yaml
Labels: chore

#376 Sort dependencies
  core/pom.xml
  groovy/pom.xml
  jelly/pom.xml
  jrebel/pom.xml
  jsp/pom.xml
Labels: skip-changelog

#370 Use `ClassValue` for caching
  core/src/main/java/org/kohsuke/stapler/AnnotationHandler.java
  core/src/main/java/org/kohsuke/stapler/ClassLoaderValue.java
  core/src/main/java/org/kohsuke/stapler/MetaClassLoader.java
  core/src/main/java/org/kohsuke/stapler/TearOffSupport.java
  core/src/main/java/org/kohsuke/stapler/WebApp.java
  core/src/main/java/org/kohsuke/stapler/export/ModelBuilder.java
  core/src/main/java/org/kohsuke/stapler/lang/Klass.java
  core/src/main/java/org/kohsuke/stapler/lang/KlassNavigator.java
  core/src/test/java/org/kohsuke/stapler/MetaClassLoaderTest.java
  groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/JellyBuilder.java
  groovy/src/test/java/org/kohsuke/stapler/jelly/groovy/GroovyClassLoaderTearOffTest.java
  jrebel/src/main/java/org/kohsuke/stapler/JRebelFacet.java
Labels: bug

#377 Use Java 11 language features where possible
  core/src/main/java/org/kohsuke/stapler/CaptureParameterNameTransformation.java
  core/src/main/java/org/kohsuke/stapler/Stapler.java
  core/src/main/java/org/kohsuke/stapler/TokenList.java
  core/src/main/java/org/kohsuke/stapler/bind/Bound.java
  core/src/main/java/org/kohsuke/stapler/export/Model.java
  core/src/main/java/org/kohsuke/stapler/jsr269/ConstructorProcessor.java
  core/src/test/java/org/kohsuke/stapler/RequestImplTest.java
  core/src/test/java/org/kohsuke/stapler/export/ModelTest.java
  core/src/test/java/org/kohsuke/stapler/export/XMLDataWriterTest.java
  core/src/test/java/org/kohsuke/stapler/lang/KlassTest.java
  groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/GroovyFacet.java
  groovy/src/test/java/org/kohsuke/stapler/jelly/groovy/GroovyClassLoaderTearOffTest.java
  jelly/src/main/java/org/kohsuke/stapler/jelly/AnnotationProcessorImpl.java
  jelly/src/main/java/org/kohsuke/stapler/jelly/InternationalizedStringExpression.java
  jelly/src/main/java/org/kohsuke/stapler/jelly/JellyFacet.java
Labels: chore

#380 Block incompatible version of JSP
  .github/dependabot.yml
Labels: dependencies, java, skip-changelog
