Repository jenkinsci/stapler, pull requests merged in 2023-05, with the labels that each got.

#452 Remove Stapler dependency on Prototype or jQuery
  core/src/main/resources/org/kohsuke/stapler/bind.js
  core/src/main/resources/org/kohsuke/stapler/framework/prototype/prototype.js
  core/src/main/resources/org/kohsuke/stapler/json2.js
  core/src/test/java/org/kohsuke/stapler/AncestorImplTest.java
  core/src/test/java/org/kohsuke/stapler/DispatcherTest.java
  core/src/test/java/org/kohsuke/stapler/Stapler2Test.java
  core/src/test/java/org/kohsuke/stapler/bind/BoundObjectTableTest.java
  core/src/test/java/org/kohsuke/stapler/bind/JavaScriptProxyTest.java
  core/src/test/java/org/kohsuke/stapler/interceptor/JsonOutputFilterTest.java
  core/src/test/java/org/kohsuke/stapler/json/JsonBodyTest.java
  core/src/test/java/org/kohsuke/stapler/json/SubmittedFormTest.java
  core/src/test/java/org/kohsuke/stapler/test/JettyTestCase.java
  jelly/pom.xml
  jelly/src/main/java/org/kohsuke/stapler/jelly/BindTag.java
  jelly/src/test/java/org/kohsuke/stapler/jelly/AttributeExpressionTest.java
  jelly/src/test/java/org/kohsuke/stapler/jelly/BindTagJQueryTest.java
  jelly/src/test/java/org/kohsuke/stapler/jelly/BindTagTest.java
  jelly/src/test/java/org/kohsuke/stapler/jelly/BodyExpressionTest.java
  jelly/src/test/java/org/kohsuke/stapler/jelly/TagLibNamespaceExportTest.java
  jelly/src/test/java/org/kohsuke/stapler/jelly/issue76/Issue76Test.java
  jelly/src/test/resources/org/kohsuke/stapler/jelly/BindTagJQueryTest/index.jelly
Labels: removed

#459 [JENKINS-71236] Stapler Ajax Proxy is broken (regression in 2.404)
  core/src/main/resources/org/kohsuke/stapler/bind.js
Labels: bug

#460 Adjust Stapler parent module name and description
  pom.xml
Labels: chore

#464 Update htmlunit to 3.x
  core/src/test/java/org/kohsuke/stapler/AncestorImplTest.java
  core/src/test/java/org/kohsuke/stapler/DispatcherTest.java
  core/src/test/java/org/kohsuke/stapler/Stapler2Test.java
  core/src/test/java/org/kohsuke/stapler/bind/BoundObjectTableTest.java
  core/src/test/java/org/kohsuke/stapler/bind/JavaScriptProxyTest.java
  core/src/test/java/org/kohsuke/stapler/interceptor/JsonOutputFilterTest.java
  core/src/test/java/org/kohsuke/stapler/json/JsonBodyTest.java
  core/src/test/java/org/kohsuke/stapler/json/SubmittedFormTest.java
  core/src/test/java/org/kohsuke/stapler/test/JettyTestCase.java
  jelly/src/test/java/org/kohsuke/stapler/jelly/AttributeExpressionTest.java
  jelly/src/test/java/org/kohsuke/stapler/jelly/BindTagTest.java
  jelly/src/test/java/org/kohsuke/stapler/jelly/BodyExpressionTest.java
  jelly/src/test/java/org/kohsuke/stapler/jelly/TagLibNamespaceExportTest.java
  jelly/src/test/java/org/kohsuke/stapler/jelly/issue76/Issue76Test.java
  pom.xml
Labels: dependencies
