Repository jenkinsci/stapler, pull requests merged in 2025-02, with the labels that each got.

#638 [JENKINS-75224] Remove support for `?jsonp` parameter in JSON flavor
  core/src/main/java/org/kohsuke/stapler/ResponseImpl.java
Labels: enhancement

#641 Removing GSP support
  groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/GroovyClassLoaderTearOff.java
  groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/GroovyFacet.java
  groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/GroovyServerPageScript.java
  groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/GroovyServerPageTearOff.java
  groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/SimpleTemplateParser.java
Labels: breaking

#631 [JENKINS-70756] Incorrect `RequestImpl.getParameterMap`
  core/src/main/java/org/kohsuke/stapler/RequestImpl.java
  core/src/test/java/org/kohsuke/stapler/DataBindingTest.java
  core/src/test/java/org/kohsuke/stapler/MockRequest.java
  core/src/test/java/org/kohsuke/stapler/RequestImplTest.java
Labels: bug
